[2024-05-07 17:11:39,741] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: research_scraper.research_scraper manual__2024-05-07T16:55:26.590912+00:00 [queued]>
[2024-05-07 17:11:39,755] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: research_scraper.research_scraper manual__2024-05-07T16:55:26.590912+00:00 [queued]>
[2024-05-07 17:11:39,755] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 17:11:39,755] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2024-05-07 17:11:39,756] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-05-07 17:11:39,774] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): research_scraper> on 2024-05-07 16:55:26.590912+00:00
[2024-05-07 17:11:39,800] {standard_task_runner.py:52} INFO - Started process 189 to run task
[2024-05-07 17:11:39,805] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'research_scraper', 'research_scraper', 'manual__2024-05-07T16:55:26.590912+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/ResearchScraper.py', '--cfg-path', '/tmp/tmp14lofjqf', '--error-file', '/tmp/tmp4ss8owb9']
[2024-05-07 17:11:39,807] {standard_task_runner.py:80} INFO - Job 181: Subtask research_scraper
[2024-05-07 17:11:39,913] {task_command.py:369} INFO - Running <TaskInstance: research_scraper.research_scraper manual__2024-05-07T16:55:26.590912+00:00 [running]> on host b29e3e3252f3
[2024-05-07 17:11:40,055] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=research_scraper
AIRFLOW_CTX_TASK_ID=research_scraper
AIRFLOW_CTX_EXECUTION_DATE=2024-05-07T16:55:26.590912+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-07T16:55:26.590912+00:00
[2024-05-07 17:11:40,083] {conn.py:1532} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-05-07 17:11:40,085] {conn.py:316} ERROR - DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
[2024-05-07 17:11:40,085] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-05-07 17:11:40,088] {conn.py:1532} WARNING - DNS lookup failed for kafka:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-05-07 17:11:40,089] {conn.py:316} ERROR - DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
[2024-05-07 17:11:40,089] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ResearchScraper.py", line 30, in call_scopus
    get_scopus_data()
  File "/opt/airflow/dags/scopus.py", line 54, in get_scopus_data
    producer = start_kafka_producer()
  File "/opt/airflow/dags/scopus.py", line 11, in start_kafka_producer
    producer = KafkaProducer(bootstrap_servers='kafka:9092')
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-05-07 17:11:40,105] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=research_scraper, task_id=research_scraper, execution_date=20240507T165526, start_date=20240507T171139, end_date=20240507T171140
[2024-05-07 17:11:40,130] {standard_task_runner.py:97} ERROR - Failed to execute job 181 for task research_scraper (NoBrokersAvailable; 189)
[2024-05-07 17:11:40,158] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-07 17:11:40,232] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
